name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        "CFLAGS='-Wall -O2 -g' CPPFLAGS='-I/usr/local/include' LDFLAGS='-L/usr/local/lib' \
        ./module/configure"
    - name: make test
      run: make -C module test
    - name: make
      run: make -C module
