name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        sudo apt-get update && sudo apt-get install zsh -yq
    - name: configure
      run: |
        CPPFLAGS=-I/usr/local/include CFLAGS="-g -Wall -O3" LDFLAGS=-L/usr/local/lib \
        ./module/configure --without-tcsetpgrp
    - name: make
      run: make -C module
