---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install librime-dev
      - name: Build
        # configure: error: no controlling tty
        # Try running configure with --with-tcsetpgrp or --without-tcsetpgrp
        run: |
          cd module
          ./configure --without-tcsetpgrp
          make
